#Name: YASH CHOUDHARY
#UID: 704630134
#EMAIL: yashc@g.ucla.edu

default:
	gcc -o lab1a lab1a.c
clean:
	rm -rf lab1a lab1a-704630134.tar.gz
dist:
	tar -czf lab1a-704630134.tar.gz lab1a.c Makefile README
